const express = require("express")
const { getTest } = require("../controllers/question.controller")
const router = express.Router()
const {registerUser,authenticateUser, getDashboard, dashboard, uploadFile} = require("../controllers/user.controller")
router.get("/dashboard",getDashboard)
router.post("/test",getTest)
router.post("/signup",registerUser)
router.post("/signin",authenticateUser)
router.post("/dashboard", dashboard)
router.post("/upload",uploadFile)
// router.post("/score", postScore)
module.exports = router;